export const siteConfig = {
  name: "SnapVee - Universal Social Media Video Downloader",
  description:
    "SnapVee is the ultimate social media video downloader. Download videos from TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili, Douyin, Kuaishou and more platforms. Free, fast, no watermark.",
  url: "https://snapvee.com",
  ogImage: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
  keywords: [
    "social media video downloader",
    "video download tool",
    "TikTok downloader",
    "Instagram downloader",
    "YouTube downloader",
    "YouTube Shorts downloader",
    "Facebook downloader",
    "Twitter downloader",
    "Bilibili downloader",
    "Douyin downloader",
    "Kuaishou downloader",
    "Threads downloader",
    "Pinterest downloader",
    "Vimeo downloader",
    "RedNote downloader",
    "free video download",
    "no watermark download",
    "Free video downloads",
    "No watermark download",
    "High definition video download",
    "Batch Download",
    "No need to log in",
    "Free to use",
    "Quick Download",
    "tiktok downloader",
    "youtube to downloader",
    "youtube shorts download hd",
    "instagram reels downloader",
    "instagram video downloader 4k",
    "facebook video downloader",
    "facebook story download",
    "twitter video downloader hd",
    "douyin video downloader",
    "bilibili video downloader",
    "pinterest video downloader hd 4k",
    "vimeo downloader",
    "rednote video downloader",
    "threads video downloader",
    "video downloader no watermark",
    "hd video downloader",
    "4k video downloader",
    "batch video downloader",
    "bulk video downloader",
    "download video from link",
    "save video from link",
    "online video downloader",
    "社媒视频下载器",
    "视频下载工具",
    "抖音下载器",
    "快手下载器",
    "B站下载器",
    "YouTube下载器",
    "YouTube Shorts下载器",
    "Facebook下载器",
    "Twitter下载器",
    "Douyin下载器",
    "Kuaishou下载器",
    "Threads下载器",
    "Pinterest下载器",
    "Vimeo下载器",
    "小红书下载器",
    "Pornhub downloader",
    "Pornhub video downloader",
    "download Pornhub videos",
    "Pornhub下载器",
    "免费视频下载",
    "无水印下载",
    "高清视频下载",
    "批量下载",
    "无需登录",
    "免费使用",
    "快速下载",
  ],
  author: "SnapVee Team",
  version: "2.0.0",
  lastUpdated: "2025-01-27",
};

export const defaultMetadata = {
  // 主站 SEO 配置
  en: {
    title: "SnapVee - Social Media Video Downloader | Free Tool",
    description:
      "SnapVee is the free social media video downloader. Download from TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili and more. Fast, no watermark, HD quality.",
    keywords:
      "tiktok downloader, youtube downloader, instagram downloader, social media video downloader, no watermark, HD download",
    manifest: "/manifest.json",
    openGraph: {
      title: "SnapVee - Social Media Video Downloader | Free Tool",
      description:
        "SnapVee is the free social media video downloader. Download from TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili and more. Fast, no watermark, HD quality.",
      type: "website",
      url: "https://snapvee.com/en",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - Social Media Video Downloader",
        },
      ],
      locale: "en_US",
    },
    twitter: {
      card: "summary_large_image",
      title: "SnapVee - Social Media Video Downloader",
      description:
        "Download videos from all major social media platforms. Free, fast, no watermark, HD quality. Support TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili, Douyin, Kuaishou, Threads and more.",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: "https://snapvee.com/en",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description:
          "Universal social media video downloader. Download videos from TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili, Douyin, Kuaishou, Threads and more platforms.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        author: {
          "@type": "Organization",
          name: "SnapVee",
          url: "https://snapvee.com",
          logo: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        },
        featureList: [
          "Universal social media video download",
          "Support 15+ platforms",
          "No watermark download",
          "HD quality support",
          "Batch download",
          "No login required",
          "Free to use",
          "Fast download speed",
          "Mobile friendly",
          "Privacy protected",
        ],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        releaseNotes:
          "Universal social media video downloader supporting all major platforms with enhanced features",
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          reviewCount: "1250",
        },
      }),
    },
  },
  zh: {
    title:
      "SnapVee 万能社媒视频下载器 - 抖音/YouTube/Instagram 免费高清无水印下载",
    description:
      "SnapVee 是万能的社媒视频下载工具，支持抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小红书、Threads等平台视频下载。免费、快速、无水印、高清画质。",
    keywords:
      "抖音下载器, YouTube视频下载, Instagram视频下载, Facebook视频下载, Twitter视频下载, 无水印下载, 高清视频下载, 批量下载",
    openGraph: {
      title:
        "SnapVee 万能社媒视频下载器 - 抖音/YouTube/Instagram 免费高清无水印下载",
      description:
        "SnapVee 是万能的社媒视频下载工具，支持抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小红书、Threads等平台视频下载。免费、快速、无水印、高清画质。",
      type: "website",
      url: "https://snapvee.com/zh",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - 万能社媒视频下载器",
        },
      ],
      locale: "zh",
    },
    twitter: {
      card: "summary_large_image",
      title:
        "SnapVee 万能社媒视频下载器 - 抖音/YouTube/Instagram 免费高清无水印下载",
      description:
        "支持所有主流社媒平台的视频下载。免费、快速、无水印、高清画质。支持抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小红书、Threads等平台。",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: "https://snapvee.com/zh",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description:
          "万能社媒视频下载器。支持抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小红书、Threads等平台的视频下载。",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        author: {
          "@type": "Organization",
          name: "SnapVee",
          url: "https://snapvee.com",
          logo: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        },
        featureList: [
          "万能社媒视频下载",
          "支持15+平台",
          "无水印下载",
          "高清画质支持",
          "批量下载",
          "无需登录",
          "免费使用",
          "快速下载",
          "移动端友好",
          "隐私保护",
        ],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        releaseNotes: "万能社媒视频下载器，支持所有主流平台，功能更强大",
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          reviewCount: "1250",
        },
      }),
    },
  },
  // 韩语版本
  ko: {
    title: "SnapVee - 만능 소셜 미디어 동영상 다운로더 | 무료 온라인 도구",
    description:
      "SnapVee는 만능 소셜 미디어 동영상 다운로드 도구입니다. Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Threads 등 지원. 무료, 빠름, 워터마크 없음, 고화질.",
    keywords:
      "틱톡 다운로더, 유튜브 영상 다운로드, 인스타그램 릴스 다운로드, 소셜 미디어 동영상 다운로더, 워터마크 없는 다운로드",
    openGraph: {
      title: "SnapVee - 만능 소셜 미디어 동영상 다운로더 | 무료 온라인 도구",
      description:
        "SnapVee는 만능 소셜 미디어 동영상 다운로드 도구입니다. Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Threads 등 지원. 무료, 빠름, 워터마크 없음, 고화질.",
      type: "website",
      url: "https://snapvee.com/ko",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - 만능 소셜 미디어 동영상 다운로더",
        },
      ],
      locale: "ko",
    },
    twitter: {
      card: "summary_large_image",
      title: "SnapVee - 만능 소셜 미디어 동영상 다운로더",
      description:
        "모든 주요 소셜 미디어 플랫폼의 동영상 다운로드를 지원합니다. 무료, 빠름, 워터마크 없음, 고화질. Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Xiaohongshu, Threads 등 플랫폼 지원.",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: "https://snapvee.com/ko",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description:
          "만능 소셜 미디어 동영상 다운로더. Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Xiaohongshu, Threads 등 플랫폼의 동영상 다운로드를 지원합니다.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        author: {
          "@type": "Organization",
          name: "SnapVee",
          url: "https://snapvee.com",
          logo: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        },
        featureList: [
          "만능 소셜 미디어 동영상 다운로드",
          "15개 이상 플랫폼 지원",
          "워터마크 없는 다운로드",
          "고화질 지원",
          "일괄 다운로드",
          "로그인 불필요",
          "무료 사용",
          "빠른 다운로드",
          "모바일 친화적",
          "개인정보 보호",
        ],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        releaseNotes:
          "만능 소셜 미디어 동영상 다운로더, 모든 주요 플랫폼 지원, 더욱 강력한 기능",
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          reviewCount: "1250",
        },
      }),
    },
  },

  // 日语版本
  ja: {
    title:
      "SnapVee - 万能ソーシャルメディア動画ダウンローダー | 無料オンラインツール",
    description:
      "SnapVeeは万能のソーシャルメディア動画ダウンロードツールです。Douyin、Kuaishou、Instagram、YouTube、Facebook、Twitter、Bilibili、Xiaohongshu、Threadsなどのプラットフォームの動画ダウンロードに対応。無料、高速、透かしなし、高画質。",
    keywords:
      "TikTokダウンローダー, YouTube動画保存, Instagramリール保存, ソーシャルメディア動画ダウンローダー, 透かしなしダウンロード",
    openGraph: {
      title:
        "SnapVee - 万能ソーシャルメディア動画ダウンローダー | 無料オンラインツール",
      description:
        "SnapVeeは万能のソーシャルメディア動画ダウンロードツールです。Douyin、Kuaishou、Instagram、YouTube、Facebook、Twitter、Bilibili、Xiaohongshu、Threadsなどのプラットフォームの動画ダウンロードに対応。無料、高速、透かしなし、高画質。",
      type: "website",
      url: "https://snapvee.com/ja",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - 万能ソーシャルメディア動画ダウンローダー",
        },
      ],
      locale: "ja",
    },
    twitter: {
      card: "summary_large_image",
      title: "SnapVee - 万能ソーシャルメディア動画ダウンローダー",
      description:
        "すべての主要ソーシャルメディアプラットフォームの動画ダウンロードに対応。無料、高速、透かしなし、高画質。Douyin、Kuaishou、Instagram、YouTube、Facebook、Twitter、Bilibili、Xiaohongshu、Threadsなどのプラットフォームに対応。",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: "https://snapvee.com/ja",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description:
          "万能ソーシャルメディア動画ダウンローダー。Douyin、Kuaishou、Instagram、YouTube、Facebook、Twitter、Bilibili、Xiaohongshu、Threadsなどのプラットフォームの動画ダウンロードに対応しています。",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        author: {
          "@type": "Organization",
          name: "SnapVee",
          url: "https://snapvee.com",
          logo: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        },
        featureList: [
          "万能ソーシャルメディア動画ダウンロード",
          "15以上のプラットフォームに対応",
          "透かしなしダウンロード",
          "高画質対応",
          "一括ダウンロード",
          "ログイン不要",
          "無料利用",
          "高速ダウンロード",
          "モバイルフレンドリー",
          "プライバシー保護",
        ],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        releaseNotes:
          "万能ソーシャルメディア動画ダウンローダー、すべての主要プラットフォームに対応、より強力な機能",
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          reviewCount: "1250",
        },
      }),
    },
  },

  // 印度语（印地语）版本
  hi: {
    title: "SnapVee - सोशल मीडिया वीडियो डाउनलोडर | मुफ्त टूल",
    description:
      "SnapVee: TikTok, Instagram, YouTube, Facebook, Twitter आदि से वीडियो डाउनलोड। मुफ्त, तेज़, वॉटरमार्क रहित, HD गुणवत्ता।",
    keywords:
      "tiktok downloader, youtube download, instagram download, सोशल मीडिया वीडियो डाउनलोडर, वॉटरमार्क रहित",
    openGraph: {
      title: "SnapVee - सोशल मीडिया वीडियो डाउनलोडर | मुफ्त टूल",
      description:
        "SnapVee: TikTok, Instagram, YouTube, Facebook, Twitter आदि से वीडियो डाउनलोड। मुफ्त, तेज़, वॉटरमार्क रहित, HD गुणवत्ता।",
      type: "website",
      url: "https://snapvee.com/hi",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - सोशल मीडिया वीडियो डाउनलोडर",
        },
      ],
      locale: "hi",
    },
    twitter: {
      card: "summary_large_image",
      title: "SnapVee - सोशल मीडिया वीडियो डाउनलोडर",
      description:
        "सभी प्रमुख सोशल मीडिया प्लेटफ़ॉर्म के वीडियो डाउनलोड का समर्थन करता है। मुफ्त, तेज़, वॉटरमार्क रहित, उच्च गुणवत्ता। Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Xiaohongshu, Threads आदि प्लेटफ़ॉर्म का समर्थन।",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    alternates: {
      canonical: "https://snapvee.com/hi",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description:
          "सर्वश्रेष्ठ सोशल मीडिया वीडियो डाउनलोडर। Douyin, Kuaishou, Instagram, YouTube, Facebook, Twitter, Bilibili, Xiaohongshu, Threads आदि प्लेटफ़ॉर्म के वीडियो डाउनलोड का समर्थन करता है।",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
        },
        author: {
          "@type": "Organization",
          name: "SnapVee",
          url: "https://snapvee.com",
          logo: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        },
        featureList: [
          "सर्वश्रेष्ठ सोशल मीडिया वीडियो डाउनलोड",
          "15+ प्लेटफ़ॉर्म समर्थित",
          "वॉटरमार्क रहित डाउनलोड",
          "उच्च गुणवत्ता समर्थन",
          "बैच डाउनलोड",
          "लॉगिन की आवश्यकता नहीं",
          "मुफ्त उपयोग",
          "तेज़ डाउनलोड",
          "मोबाइल फ्रेंडली",
          "गोपनीयता सुरक्षा",
        ],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        releaseNotes:
          "सर्वश्रेष्ठ सोशल मीडिया वीडियो डाउनलोडर, सभी प्रमुख प्लेटफ़ॉर्म समर्थित, अधिक शक्तिशाली सुविधाएं",
        aggregateRating: {
          "@type": "AggregateRating",
          ratingValue: "4.8",
          reviewCount: "1250",
        },
      }),
    },
  },

  // 繁体中文
  "zh-TW": {
    title: "SnapVee - 萬能社媒影片下載器 | 免費工具",
    description:
      "SnapVee 萬能社媒影片下載工具，支援抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小紅書等。免費、快速、無水印、高清。",
    keywords: "抖音下載, YouTube下載, Instagram下載, 影片下載器, 無水印",
    openGraph: {
      title: "SnapVee - 萬能社媒影片下載器 | 免費工具",
      description:
        "SnapVee 萬能社媒影片下載工具，支援抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小紅書等。免費、快速、無水印、高清。",
      type: "website",
      url: "https://snapvee.com/zh-TW",
      siteName: "SnapVee",
      images: [
        {
          url: "https://oss.api-service.net.cn/snapvee/images/twitter.png",
          width: 1200,
          height: 630,
          alt: "SnapVee - 萬能社媒影片下載器",
        },
      ],
      locale: "zh_TW",
    },
    twitter: {
      card: "summary_large_image",
      title: "SnapVee - 萬能社媒影片下載器",
      description: "支援所有主流社媒平台影片下載。免費、快速、無水印、高清。",
      images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"],
      site: "@snapvee",
    },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/zh-TW",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "萬能社媒影片下載器。支援抖音、快手、Instagram、YouTube、Facebook、Twitter、B站、小紅書等。",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["萬能社媒影片下載", "15+ 平台支援", "無水印下載", "高清支援", "批量下載", "無需登入", "免費使用", "快速下載", "行動友善", "隱私保護"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 西班牙语
  es: {
    title: "SnapVee - Descargador de videos de redes sociales | Herramienta gratis",
    description:
      "SnapVee descarga videos de TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili y más. Gratis, rápido, sin marca de agua, HD.",
    keywords: "descargar tiktok, descargar youtube, descargar instagram, descargador de videos, sin marca de agua",
    openGraph: {
      title: "SnapVee - Descargador de videos de redes sociales | Herramienta gratis",
      description: "SnapVee descarga videos de TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili y más. Gratis, rápido, sin marca de agua, HD.",
      type: "website",
      url: "https://snapvee.com/es",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "es",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Descargador de videos de redes sociales. Gratis, rápido, sin marca de agua.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/es",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Descargador de videos de redes sociales. Soporta TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili y más.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Descarga de videos", "15+ plataformas", "Sin marca de agua", "HD", "Descarga por lotes", "Sin registro", "Gratis", "Rápido", "Móvil", "Privacidad"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 葡萄牙语
  pt: {
    title: "SnapVee - Baixador de vídeos de redes sociais | Ferramenta grátis",
    description:
      "SnapVee baixa vídeos do TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e mais. Grátis, rápido, sem marca d'água, HD.",
    keywords: "baixar tiktok, baixar youtube, baixar instagram, baixador de vídeos, sem marca d'água",
    openGraph: {
      title: "SnapVee - Baixador de vídeos de redes sociais | Ferramenta grátis",
      description: "SnapVee baixa vídeos do TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e mais. Grátis, rápido, sem marca d'água, HD.",
      type: "website",
      url: "https://snapvee.com/pt",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "pt",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Baixador de vídeos de redes sociais. Grátis, rápido, sem marca d'água.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/pt",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Baixador de vídeos de redes sociais. Suporta TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e mais.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Download de vídeos", "15+ plataformas", "Sem marca d'água", "HD", "Download em lote", "Sem cadastro", "Grátis", "Rápido", "Mobile", "Privacidade"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 俄语
  ru: {
    title: "SnapVee - Загрузчик видео из соцсетей | Бесплатный инструмент",
    description:
      "SnapVee загружает видео с TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili и других. Бесплатно, быстро, без водяных знаков, HD.",
    keywords: "скачать тикток, скачать youtube, скачать инстаграм, загрузчик видео, без водяных знаков",
    openGraph: {
      title: "SnapVee - Загрузчик видео из соцсетей | Бесплатный инструмент",
      description: "SnapVee загружает видео с TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili и других. Бесплатно, быстро, без водяных знаков, HD.",
      type: "website",
      url: "https://snapvee.com/ru",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "ru",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Загрузчик видео из соцсетей. Бесплатно, быстро, без водяных знаков.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/ru",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Загрузчик видео из соцсетей. Поддержка TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili и других.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Загрузка видео", "15+ платформ", "Без водяных знаков", "HD", "Пакетная загрузка", "Без регистрации", "Бесплатно", "Быстро", "Мобильная версия", "Конфиденциальность"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 法语
  fr: {
    title: "SnapVee - Téléchargeur de vidéos réseaux sociaux | Outil gratuit",
    description:
      "SnapVee télécharge des vidéos depuis TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili et plus. Gratuit, rapide, sans filigrane, HD.",
    keywords: "télécharger tiktok, télécharger youtube, télécharger instagram, téléchargeur vidéo, sans filigrane",
    openGraph: {
      title: "SnapVee - Téléchargeur de vidéos réseaux sociaux | Outil gratuit",
      description: "SnapVee télécharge des vidéos depuis TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili et plus. Gratuit, rapide, sans filigrane, HD.",
      type: "website",
      url: "https://snapvee.com/fr",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "fr",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Téléchargeur de vidéos réseaux sociaux. Gratuit, rapide, sans filigrane.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/fr",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Téléchargeur de vidéos réseaux sociaux. Support TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili et plus.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Téléchargement vidéo", "15+ plateformes", "Sans filigrane", "HD", "Téléchargement par lots", "Sans inscription", "Gratuit", "Rapide", "Mobile", "Confidentialité"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 德语
  de: {
    title: "SnapVee - Social-Media-Video-Downloader | Kostenloses Tool",
    description:
      "SnapVee lädt Videos von TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili und mehr. Kostenlos, schnell, ohne Wasserzeichen, HD.",
    keywords: "tiktok herunterladen, youtube herunterladen, instagram herunterladen, videodownloader, ohne wasserzeichen",
    openGraph: {
      title: "SnapVee - Social-Media-Video-Downloader | Kostenloses Tool",
      description: "SnapVee lädt Videos von TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili und mehr. Kostenlos, schnell, ohne Wasserzeichen, HD.",
      type: "website",
      url: "https://snapvee.com/de",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "de",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Social-Media-Video-Downloader. Kostenlos, schnell, ohne Wasserzeichen.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/de",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Social-Media-Video-Downloader. Unterstützt TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili und mehr.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Video-Download", "15+ Plattformen", "Ohne Wasserzeichen", "HD", "Batch-Download", "Ohne Anmeldung", "Kostenlos", "Schnell", "Mobil", "Datenschutz"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },

  // 意大利语
  it: {
    title: "SnapVee - Scaricatore video social media | Strumento gratuito",
    description:
      "SnapVee scarica video da TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e altro. Gratis, veloce, senza filigrana, HD.",
    keywords: "scaricare tiktok, scaricare youtube, scaricare instagram, scaricatore video, senza filigrana",
    openGraph: {
      title: "SnapVee - Scaricatore video social media | Strumento gratuito",
      description: "SnapVee scarica video da TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e altro. Gratis, veloce, senza filigrana, HD.",
      type: "website",
      url: "https://snapvee.com/it",
      siteName: "SnapVee",
      images: [{ url: "https://oss.api-service.net.cn/snapvee/images/twitter.png", width: 1200, height: 630, alt: "SnapVee" }],
      locale: "it",
    },
    twitter: { card: "summary_large_image", title: "SnapVee", description: "Scaricatore video social media. Gratis, veloce, senza filigrana.", images: ["https://oss.api-service.net.cn/snapvee/images/twitter.png"], site: "@snapvee" },
    robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
    alternates: {
      canonical: "https://snapvee.com/it",
      languages: {
        en: "https://snapvee.com/en",
        zh: "https://snapvee.com/zh",
        ja: "https://snapvee.com/ja",
        ko: "https://snapvee.com/ko",
        hi: "https://snapvee.com/hi",
        "zh-TW": "https://snapvee.com/zh-TW",
        es: "https://snapvee.com/es",
        pt: "https://snapvee.com/pt",
        ru: "https://snapvee.com/ru",
        fr: "https://snapvee.com/fr",
        de: "https://snapvee.com/de",
        it: "https://snapvee.com/it",
        "x-default": "https://snapvee.com/en",
      },
    },
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "WebApplication",
        name: "SnapVee",
        description: "Scaricatore video social media. Supporta TikTok, Instagram, YouTube, Facebook, Twitter, Bilibili e altro.",
        url: "https://snapvee.com",
        applicationCategory: "MultimediaApplication",
        operatingSystem: "Web Browser",
        offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
        author: { "@type": "Organization", name: "SnapVee", url: "https://snapvee.com", logo: "https://oss.api-service.net.cn/snapvee/images/logo.png" },
        featureList: ["Download video", "15+ piattaforme", "Senza filigrana", "HD", "Download batch", "Senza registrazione", "Gratis", "Veloce", "Mobile", "Privacy"],
        screenshot: "https://oss.api-service.net.cn/snapvee/images/logo.png",
        downloadUrl: "https://snapvee.com",
        softwareVersion: "2.0.0",
        aggregateRating: { "@type": "AggregateRating", ratingValue: "4.8", reviewCount: "1250" },
      }),
    },
  },
};
